### YamlMime:ManagedReference
items:
- uid: System.Workflow.Activities.Rules.RuleException
  id: RuleException
  children:
  - System.Workflow.Activities.Rules.RuleException.#ctor
  - System.Workflow.Activities.Rules.RuleException.#ctor(System.String)
  - System.Workflow.Activities.Rules.RuleException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  - System.Workflow.Activities.Rules.RuleException.#ctor(System.String,System.Exception)
  langs:
  - csharp
  name: RuleException
  nameWithType: RuleException
  fullName: System.Workflow.Activities.Rules.RuleException
  type: Class
  summary: "ルールの評価または検証によって引き起こされるすべての例外の基底クラスを表します。"
  syntax:
    content: 'public class RuleException : Exception'
  inheritance:
  - System.Exception
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Workflow.Activities.Rules.RuleException.#ctor
  id: '#ctor'
  parent: System.Workflow.Activities.Rules.RuleException
  langs:
  - csharp
  name: RuleException()
  nameWithType: RuleException.RuleException()
  fullName: System.Workflow.Activities.Rules.RuleException.RuleException()
  type: Constructor
  assemblies:
  - System.Workflow.Activities
  namespace: System.Workflow.Activities.Rules
  summary: "新しいインスタンスを初期化、 <xref href=&quot;System.Workflow.Activities.Rules.RuleException&quot;> </xref>クラスです。"
  remarks: "このコンス トラクター、<xref:System.Exception.Message%2A>エラーを説明し、現在のシステム カルチャが考慮するシステム提供のメッセージの新しいインスタンスのプロパティ</xref:System.Exception.Message%2A>。       次の表は、 <xref:System.Workflow.Activities.Rules.RuleException>。</xref:System.Workflow.Activities.Rules.RuleException>のインスタンスの初期プロパティ値を示しています。      |プロパティ |値 |  |--------------|-----------|  |<xref:System.Exception.InnerException%2A>|Null 参照 (`Nothing` Visual Basic で). |  |<xref:System.Exception.Message%2A>|A のシステム提供のローカライズされた説明 |</xref:System.Exception.Message%2A> </xref:System.Exception.InnerException%2A> 。"
  syntax:
    content: public RuleException ();
    parameters: []
  overload: System.Workflow.Activities.Rules.RuleException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Workflow.Activities.Rules.RuleException.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.Workflow.Activities.Rules.RuleException
  langs:
  - csharp
  name: RuleException(String)
  nameWithType: RuleException.RuleException(String)
  fullName: System.Workflow.Activities.Rules.RuleException.RuleException(String)
  type: Constructor
  assemblies:
  - System.Workflow.Activities
  namespace: System.Workflow.Activities.Rules
  summary: "新しいインスタンスを初期化、 <xref href=&quot;System.Workflow.Activities.Rules.RuleException&quot;> </xref>指定したエラー メッセージを使用します。"
  remarks: "このコンス トラクター、<xref:System.Exception.Message%2A>の新しいインスタンスを使用して、プロパティ、`message`パラメーター</xref:System.Exception.Message%2A> 。       次の表は、 <xref:System.Workflow.Activities.Rules.RuleException>。</xref:System.Workflow.Activities.Rules.RuleException>のインスタンスの初期プロパティ値を示しています。      |プロパティ |値 |  |--------------|-----------|  |<xref:System.Exception.InnerException%2A>|Null 参照 (`Nothing` Visual Basic で). |  |<xref:System.Exception.Message%2A>|エラー メッセージ文字列 |</xref:System.Exception.Message%2A> </xref:System.Exception.InnerException%2A> 。"
  syntax:
    content: public RuleException (string message);
    parameters:
    - id: message
      type: System.String
      description: "エラーを説明するメッセージ。"
  overload: System.Workflow.Activities.Rules.RuleException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Workflow.Activities.Rules.RuleException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  id: '#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)'
  parent: System.Workflow.Activities.Rules.RuleException
  langs:
  - csharp
  name: RuleException(SerializationInfo,StreamingContext)
  nameWithType: RuleException.RuleException(SerializationInfo,StreamingContext)
  fullName: System.Workflow.Activities.Rules.RuleException.RuleException(SerializationInfo,StreamingContext)
  type: Constructor
  assemblies:
  - System.Workflow.Activities
  namespace: System.Workflow.Activities.Rules
  summary: "新しいインスタンスを初期化、 <xref href=&quot;System.Workflow.Activities.Rules.RuleException&quot;> </xref>シリアル化されたデータを持つクラス。"
  remarks: "このコンス トラクターは、ストリームで送信された例外オブジェクトを再構成する逆シリアル化中に呼び出されます。"
  syntax:
    content: protected RuleException (System.Runtime.Serialization.SerializationInfo serializeInfo, System.Runtime.Serialization.StreamingContext context);
    parameters:
    - id: serializeInfo
      type: System.Runtime.Serialization.SerializationInfo
      description: "<xref href=&quot;System.Runtime.Serialization.SerializationInfo&quot;> </xref>スローされた例外に関するシリアル化されたオブジェクト データを保持します。"
    - id: context
      type: System.Runtime.Serialization.StreamingContext
      description: "<xref:System.Runtime.Serialization.StreamingContext>ソースまたは転送先に関するコンテキスト情報を含む</xref:System.Runtime.Serialization.StreamingContext>。"
  overload: System.Workflow.Activities.Rules.RuleException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Workflow.Activities.Rules.RuleException.#ctor(System.String,System.Exception)
  id: '#ctor(System.String,System.Exception)'
  parent: System.Workflow.Activities.Rules.RuleException
  langs:
  - csharp
  name: RuleException(String,Exception)
  nameWithType: RuleException.RuleException(String,Exception)
  fullName: System.Workflow.Activities.Rules.RuleException.RuleException(String,Exception)
  type: Constructor
  assemblies:
  - System.Workflow.Activities
  namespace: System.Workflow.Activities.Rules
  summary: "新しいインスタンスを初期化、 <xref href=&quot;System.Workflow.Activities.Rules.RuleException&quot;> </xref>クラスは、指定したエラー メッセージと<xref:System.Exception>この<xref:System.Exception>.</xref:System.Exception>の原因である</xref:System.Exception>内部への参照"
  remarks: "<xref:System.Exception>、以前の直接の結果としてスローされる<xref:System.Exception>に前の例外への参照を含める必要があります、<xref:System.Exception.InnerException%2A>プロパティ</xref:System.Exception.InnerException%2A></xref:System.Exception></xref:System.Exception>。 <xref:System.Exception.InnerException%2A>コンス トラクター、または null 参照に渡されたものと同じ値を返します (`Nothing`) 場合、<xref:System.Exception.InnerException%2A>プロパティは、内部を指定しない<xref:System.Exception>コンス トラクターに値</xref:System.Exception></xref:System.Exception.InnerException%2A></xref:System.Exception.InnerException%2A>。       次の表は、 <xref:System.Workflow.Activities.Rules.RuleException>。</xref:System.Workflow.Activities.Rules.RuleException>のインスタンスの初期プロパティ値を示しています。      |プロパティ |値 |  |--------------|-----------|  |<xref:System.Exception.InnerException%2A>|内部<xref:System.Exception>参照 |。  |<xref:System.Exception.Message%2A>|エラー メッセージ文字列 |</xref:System.Exception.Message%2A> </xref:System.Exception> </xref:System.Exception.InnerException%2A> 。"
  syntax:
    content: public RuleException (string message, Exception ex);
    parameters:
    - id: message
      type: System.String
      description: "エラーを説明するメッセージ。"
    - id: ex
      type: System.Exception
      description: "<xref:System.Exception>現在<xref:System.Exception>。</xref:System.Exception>の原因であります。</xref:System.Exception> 場合、`innerException`パラメーターが null 参照ではありません (<xref uid=&quot;langword_csharp_Nothing&quot; name=&quot;Nothing&quot; href=&quot;&quot;> </xref> Visual Basic で)、現在の<xref:System.Exception>内部<xref:System.Exception>.</xref:System.Exception>を処理する catch ブロック内で発生しました。</xref:System.Exception>"
  overload: System.Workflow.Activities.Rules.RuleException.#ctor*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Exception
  isExternal: false
  name: System.Exception
- uid: System.Workflow.Activities.Rules.RuleException.#ctor
  parent: System.Workflow.Activities.Rules.RuleException
  isExternal: false
  name: RuleException()
  nameWithType: RuleException.RuleException()
  fullName: System.Workflow.Activities.Rules.RuleException.RuleException()
- uid: System.Workflow.Activities.Rules.RuleException.#ctor(System.String)
  parent: System.Workflow.Activities.Rules.RuleException
  isExternal: false
  name: RuleException(String)
  nameWithType: RuleException.RuleException(String)
  fullName: System.Workflow.Activities.Rules.RuleException.RuleException(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Workflow.Activities.Rules.RuleException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  parent: System.Workflow.Activities.Rules.RuleException
  isExternal: false
  name: RuleException(SerializationInfo,StreamingContext)
  nameWithType: RuleException.RuleException(SerializationInfo,StreamingContext)
  fullName: System.Workflow.Activities.Rules.RuleException.RuleException(SerializationInfo,StreamingContext)
- uid: System.Runtime.Serialization.SerializationInfo
  parent: System.Runtime.Serialization
  isExternal: false
  name: SerializationInfo
  nameWithType: SerializationInfo
  fullName: System.Runtime.Serialization.SerializationInfo
- uid: System.Runtime.Serialization.StreamingContext
  parent: System.Runtime.Serialization
  isExternal: true
  name: StreamingContext
  nameWithType: StreamingContext
  fullName: System.Runtime.Serialization.StreamingContext
- uid: System.Workflow.Activities.Rules.RuleException.#ctor(System.String,System.Exception)
  parent: System.Workflow.Activities.Rules.RuleException
  isExternal: false
  name: RuleException(String,Exception)
  nameWithType: RuleException.RuleException(String,Exception)
  fullName: System.Workflow.Activities.Rules.RuleException.RuleException(String,Exception)
- uid: System.Workflow.Activities.Rules.RuleException.#ctor*
  parent: System.Workflow.Activities.Rules.RuleException
  isExternal: false
  name: RuleException
  nameWithType: RuleException.RuleException
