### YamlMime:ManagedReference
items:
- uid: System.Data.Services.Client.DataServiceClientException
  id: DataServiceClientException
  children:
  - System.Data.Services.Client.DataServiceClientException.#ctor
  - System.Data.Services.Client.DataServiceClientException.#ctor(System.String)
  - System.Data.Services.Client.DataServiceClientException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  - System.Data.Services.Client.DataServiceClientException.#ctor(System.String,System.Exception)
  - System.Data.Services.Client.DataServiceClientException.#ctor(System.String,System.Int32)
  - System.Data.Services.Client.DataServiceClientException.#ctor(System.String,System.Exception,System.Int32)
  - System.Data.Services.Client.DataServiceClientException.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  - System.Data.Services.Client.DataServiceClientException.StatusCode
  langs:
  - csharp
  name: DataServiceClientException
  nameWithType: DataServiceClientException
  fullName: System.Data.Services.Client.DataServiceClientException
  type: Class
  summary: "実行中に発生したエラーを表します[!INCLUDE[ssAstoria](~/add/includes/ssastoria-md.md)]クライアント アプリケーション。"
  syntax:
    content: >-
      [System.Diagnostics.DebuggerDisplay("{Message}")]

      public sealed class DataServiceClientException : InvalidOperationException
  inheritance:
  - System.InvalidOperationException
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Data.Services.Client.DataServiceClientException.#ctor
  id: '#ctor'
  parent: System.Data.Services.Client.DataServiceClientException
  langs:
  - csharp
  name: DataServiceClientException()
  nameWithType: DataServiceClientException.DataServiceClientException()
  fullName: System.Data.Services.Client.DataServiceClientException.DataServiceClientException()
  type: Constructor
  assemblies:
  - System.Data.Services.Client
  namespace: System.Data.Services.Client
  summary: "新しいインスタンスを初期化、 <xref href=&quot;System.Data.Services.Client.DataServiceClientException&quot;> </xref>エラーを説明するシステム提供のメッセージを持つクラス。"
  remarks: "このコンス トラクター、<xref:System.Exception.Message%2A>エラーを説明するシステム提供のメッセージの新しいインスタンスのプロパティ</xref:System.Exception.Message%2A>。 このメッセージでは、現在のシステム カルチャが考慮されます。       次の表は、 <xref:System.InsufficientMemoryException>。</xref:System.InsufficientMemoryException>のインスタンスの初期プロパティ値を示しています。      |プロパティ |値 |  |--------------|-----------|  |<xref:System.Exception.InnerException%2A>|`null`.|  |<xref:System.Exception.Message%2A>|ローカライズされたエラー メッセージ文字列 |</xref:System.Exception.Message%2A> </xref:System.Exception.InnerException%2A> 。"
  syntax:
    content: public DataServiceClientException ();
    parameters: []
  overload: System.Data.Services.Client.DataServiceClientException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Data.Services.Client.DataServiceClientException.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.Data.Services.Client.DataServiceClientException
  langs:
  - csharp
  name: DataServiceClientException(String)
  nameWithType: DataServiceClientException.DataServiceClientException(String)
  fullName: System.Data.Services.Client.DataServiceClientException.DataServiceClientException(String)
  type: Constructor
  assemblies:
  - System.Data.Services.Client
  namespace: System.Data.Services.Client
  summary: "新しいインスタンスを初期化、 <xref href=&quot;System.Data.Services.Client.DataServiceClientException&quot;> </xref>エラーを説明するメッセージが指定されたクラスです。"
  remarks: "次の表は、 <xref:System.Data.Services.Client.DataServiceClientException>。</xref:System.Data.Services.Client.DataServiceClientException>のインスタンスの初期プロパティ値を示しています。      |プロパティ |値 |  |--------------|-----------|  |<xref:System.Exception.InnerException%2A>|`null`.|  |<xref:System.Exception.Message%2A>|指定されたエラー メッセージ文字列`message`|</xref:System.Exception.Message%2A> </xref:System.Exception.InnerException%2A> 。"
  syntax:
    content: public DataServiceClientException (string message);
    parameters:
    - id: message
      type: System.String
      description: "例外を説明するメッセージ。 このコンス トラクターの呼び出し元は、この文字列が現在のシステムのカルチャに合わせてローカライズ済みであることを確認するために必要です。"
  overload: System.Data.Services.Client.DataServiceClientException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Data.Services.Client.DataServiceClientException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  id: '#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)'
  parent: System.Data.Services.Client.DataServiceClientException
  langs:
  - csharp
  name: DataServiceClientException(SerializationInfo,StreamingContext)
  nameWithType: DataServiceClientException.DataServiceClientException(SerializationInfo,StreamingContext)
  fullName: System.Data.Services.Client.DataServiceClientException.DataServiceClientException(SerializationInfo,StreamingContext)
  type: Constructor
  assemblies:
  - System.Data.Services.Client
  namespace: System.Data.Services.Client
  syntax:
    content: protected DataServiceClientException (System.Runtime.Serialization.SerializationInfo serializationInfo, System.Runtime.Serialization.StreamingContext context);
    parameters:
    - id: serializationInfo
      type: System.Runtime.Serialization.SerializationInfo
      description: "追加します。"
    - id: context
      type: System.Runtime.Serialization.StreamingContext
      description: "追加します。"
  overload: System.Data.Services.Client.DataServiceClientException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Data.Services.Client.DataServiceClientException.#ctor(System.String,System.Exception)
  id: '#ctor(System.String,System.Exception)'
  parent: System.Data.Services.Client.DataServiceClientException
  langs:
  - csharp
  name: DataServiceClientException(String,Exception)
  nameWithType: DataServiceClientException.DataServiceClientException(String,Exception)
  fullName: System.Data.Services.Client.DataServiceClientException.DataServiceClientException(String,Exception)
  type: Constructor
  assemblies:
  - System.Data.Services.Client
  namespace: System.Data.Services.Client
  summary: "新しいインスタンスを初期化、 <xref href=&quot;System.Data.Services.Client.DataServiceClientException&quot;> </xref>指定したエラー メッセージおよびこの例外の原因となった内部例外への参照を持つクラス。"
  remarks: "前の例外への参照を含める必要があります前の例外の直接の結果としてスローされる例外、<xref:System.Exception.InnerException%2A>プロパティ</xref:System.Exception.InnerException%2A>。 <xref:System.Exception.InnerException%2A>プロパティは、コンス トラクターに渡されたものと同じ値を返しますまたは`null`場合、<xref:System.Exception.InnerException%2A>プロパティがコンス トラクターには、内部例外値を指定していません</xref:System.Exception.InnerException%2A></xref:System.Exception.InnerException%2A>。       次の表は、 <xref:System.Data.Services.Client.DataServiceClientException>。</xref:System.Data.Services.Client.DataServiceClientException>のインスタンスの初期プロパティ値を示しています。      |プロパティ |値 |  |--------------|-----------|  |<xref:System.Exception.InnerException%2A>|`null`.|  |<xref:System.Exception.Message%2A>|指定されたエラー メッセージ文字列`message`|</xref:System.Exception.Message%2A> </xref:System.Exception.InnerException%2A> 。"
  syntax:
    content: public DataServiceClientException (string message, Exception innerException);
    parameters:
    - id: message
      type: System.String
      description: "例外を説明するメッセージ。 このコンス トラクターの呼び出し元は、この文字列が現在のシステムのカルチャに合わせてローカライズ済みであることを確認するために必要です。"
    - id: innerException
      type: System.Exception
      description: "現在の例外の原因となった例外。 場合、`innerException`パラメーター <xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;></xref>で現在の例外が発生、 <xref uid=&quot;langword_csharp_catch&quot; name=&quot;catch&quot; href=&quot;&quot;> </xref>ブロックは、内部例外を処理します。"
  overload: System.Data.Services.Client.DataServiceClientException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Data.Services.Client.DataServiceClientException.#ctor(System.String,System.Int32)
  id: '#ctor(System.String,System.Int32)'
  parent: System.Data.Services.Client.DataServiceClientException
  langs:
  - csharp
  name: DataServiceClientException(String,Int32)
  nameWithType: DataServiceClientException.DataServiceClientException(String,Int32)
  fullName: System.Data.Services.Client.DataServiceClientException.DataServiceClientException(String,Int32)
  type: Constructor
  assemblies:
  - System.Data.Services.Client
  namespace: System.Data.Services.Client
  summary: "新しいインスタンスを初期化、 <xref href=&quot;System.Data.Services.Client.DataServiceClientException&quot;> </xref>クラスです。"
  syntax:
    content: public DataServiceClientException (string message, int statusCode);
    parameters:
    - id: message
      type: System.String
      description: "エラー メッセージを含む文字列値。"
    - id: statusCode
      type: System.Int32
      description: "ステータス コードを含む整数値。"
  overload: System.Data.Services.Client.DataServiceClientException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Data.Services.Client.DataServiceClientException.#ctor(System.String,System.Exception,System.Int32)
  id: '#ctor(System.String,System.Exception,System.Int32)'
  parent: System.Data.Services.Client.DataServiceClientException
  langs:
  - csharp
  name: DataServiceClientException(String,Exception,Int32)
  nameWithType: DataServiceClientException.DataServiceClientException(String,Exception,Int32)
  fullName: System.Data.Services.Client.DataServiceClientException.DataServiceClientException(String,Exception,Int32)
  type: Constructor
  assemblies:
  - System.Data.Services.Client
  namespace: System.Data.Services.Client
  summary: "新しいインスタンスを初期化、 <xref href=&quot;System.Data.Services.Client.DataServiceClientException&quot;> </xref>クラスです。"
  syntax:
    content: public DataServiceClientException (string message, Exception innerException, int statusCode);
    parameters:
    - id: message
      type: System.String
      description: "エラー メッセージを含む文字列値。"
    - id: innerException
      type: System.Exception
      description: "<xref uid=&quot;langword_csharp_System.Exception&quot; name=&quot;System.Exception&quot; href=&quot;&quot;> </xref>内部例外を含むオブジェクトです。"
    - id: statusCode
      type: System.Int32
      description: "ステータス コードを含む整数値。"
  overload: System.Data.Services.Client.DataServiceClientException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Data.Services.Client.DataServiceClientException.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  id: GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  parent: System.Data.Services.Client.DataServiceClientException
  langs:
  - csharp
  name: GetObjectData(SerializationInfo,StreamingContext)
  nameWithType: DataServiceClientException.GetObjectData(SerializationInfo,StreamingContext)
  fullName: System.Data.Services.Client.DataServiceClientException.GetObjectData(SerializationInfo,StreamingContext)
  type: Method
  assemblies:
  - System.Data.Services.Client
  namespace: System.Data.Services.Client
  summary: "新しいインスタンスを初期化、 <xref href=&quot;System.Data.Services.Client.DataServiceClientException&quot;> </xref>シリアル化されたデータを持つクラス。"
  remarks: "このコンス トラクターは、ストリームで送信された例外オブジェクトを再構成する逆シリアル化中に呼び出されます。 詳細については、次を参照してください。 [XML および SOAP シリアル化](~/add/includes/ajax-current-ext-md.md)です。"
  syntax:
    content: public override void GetObjectData (System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);
    parameters:
    - id: info
      type: System.Runtime.Serialization.SerializationInfo
      description: "シリアル化されたオブジェクト データを保持するオブジェクト。"
    - id: context
      type: System.Runtime.Serialization.StreamingContext
      description: "ソースまたは転送先に関する文脈情報。"
  overload: System.Data.Services.Client.DataServiceClientException.GetObjectData*
  exceptions: []
  platform:
  - net462
- uid: System.Data.Services.Client.DataServiceClientException.StatusCode
  id: StatusCode
  parent: System.Data.Services.Client.DataServiceClientException
  langs:
  - csharp
  name: StatusCode
  nameWithType: DataServiceClientException.StatusCode
  fullName: System.Data.Services.Client.DataServiceClientException.StatusCode
  type: Property
  assemblies:
  - System.Data.Services.Client
  namespace: System.Data.Services.Client
  summary: "後に返される HTTP エラー状態コードを取得<xref href=&quot;System.Data.Services.Client.DataServiceClientException&quot;></xref>です。"
  syntax:
    content: public int StatusCode { get; }
    return:
      type: System.Int32
      description: "例外を表す整数値。"
  overload: System.Data.Services.Client.DataServiceClientException.StatusCode*
  exceptions: []
  platform:
  - net462
references:
- uid: System.InvalidOperationException
  isExternal: false
  name: System.InvalidOperationException
- uid: System.Data.Services.Client.DataServiceClientException.#ctor
  parent: System.Data.Services.Client.DataServiceClientException
  isExternal: false
  name: DataServiceClientException()
  nameWithType: DataServiceClientException.DataServiceClientException()
  fullName: System.Data.Services.Client.DataServiceClientException.DataServiceClientException()
- uid: System.Data.Services.Client.DataServiceClientException.#ctor(System.String)
  parent: System.Data.Services.Client.DataServiceClientException
  isExternal: false
  name: DataServiceClientException(String)
  nameWithType: DataServiceClientException.DataServiceClientException(String)
  fullName: System.Data.Services.Client.DataServiceClientException.DataServiceClientException(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Data.Services.Client.DataServiceClientException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  parent: System.Data.Services.Client.DataServiceClientException
  isExternal: false
  name: DataServiceClientException(SerializationInfo,StreamingContext)
  nameWithType: DataServiceClientException.DataServiceClientException(SerializationInfo,StreamingContext)
  fullName: System.Data.Services.Client.DataServiceClientException.DataServiceClientException(SerializationInfo,StreamingContext)
- uid: System.Runtime.Serialization.SerializationInfo
  parent: System.Runtime.Serialization
  isExternal: false
  name: SerializationInfo
  nameWithType: SerializationInfo
  fullName: System.Runtime.Serialization.SerializationInfo
- uid: System.Runtime.Serialization.StreamingContext
  parent: System.Runtime.Serialization
  isExternal: true
  name: StreamingContext
  nameWithType: StreamingContext
  fullName: System.Runtime.Serialization.StreamingContext
- uid: System.Data.Services.Client.DataServiceClientException.#ctor(System.String,System.Exception)
  parent: System.Data.Services.Client.DataServiceClientException
  isExternal: false
  name: DataServiceClientException(String,Exception)
  nameWithType: DataServiceClientException.DataServiceClientException(String,Exception)
  fullName: System.Data.Services.Client.DataServiceClientException.DataServiceClientException(String,Exception)
- uid: System.Exception
  parent: System
  isExternal: true
  name: Exception
  nameWithType: Exception
  fullName: System.Exception
- uid: System.Data.Services.Client.DataServiceClientException.#ctor(System.String,System.Int32)
  parent: System.Data.Services.Client.DataServiceClientException
  isExternal: false
  name: DataServiceClientException(String,Int32)
  nameWithType: DataServiceClientException.DataServiceClientException(String,Int32)
  fullName: System.Data.Services.Client.DataServiceClientException.DataServiceClientException(String,Int32)
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.Data.Services.Client.DataServiceClientException.#ctor(System.String,System.Exception,System.Int32)
  parent: System.Data.Services.Client.DataServiceClientException
  isExternal: false
  name: DataServiceClientException(String,Exception,Int32)
  nameWithType: DataServiceClientException.DataServiceClientException(String,Exception,Int32)
  fullName: System.Data.Services.Client.DataServiceClientException.DataServiceClientException(String,Exception,Int32)
- uid: System.Data.Services.Client.DataServiceClientException.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  parent: System.Data.Services.Client.DataServiceClientException
  isExternal: false
  name: GetObjectData(SerializationInfo,StreamingContext)
  nameWithType: DataServiceClientException.GetObjectData(SerializationInfo,StreamingContext)
  fullName: System.Data.Services.Client.DataServiceClientException.GetObjectData(SerializationInfo,StreamingContext)
- uid: System.Data.Services.Client.DataServiceClientException.StatusCode
  parent: System.Data.Services.Client.DataServiceClientException
  isExternal: false
  name: StatusCode
  nameWithType: DataServiceClientException.StatusCode
  fullName: System.Data.Services.Client.DataServiceClientException.StatusCode
- uid: System.Data.Services.Client.DataServiceClientException.#ctor*
  parent: System.Data.Services.Client.DataServiceClientException
  isExternal: false
  name: DataServiceClientException
  nameWithType: DataServiceClientException.DataServiceClientException
- uid: System.Data.Services.Client.DataServiceClientException.GetObjectData*
  parent: System.Data.Services.Client.DataServiceClientException
  isExternal: false
  name: GetObjectData
  nameWithType: DataServiceClientException.GetObjectData
- uid: System.Data.Services.Client.DataServiceClientException.StatusCode*
  parent: System.Data.Services.Client.DataServiceClientException
  isExternal: false
  name: StatusCode
  nameWithType: DataServiceClientException.StatusCode
