### YamlMime:ManagedReference
items:
- uid: System.IO.IsolatedStorage.IsolatedStorageException
  id: IsolatedStorageException
  children:
  - System.IO.IsolatedStorage.IsolatedStorageException.#ctor
  - System.IO.IsolatedStorage.IsolatedStorageException.#ctor(System.String)
  - System.IO.IsolatedStorage.IsolatedStorageException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  - System.IO.IsolatedStorage.IsolatedStorageException.#ctor(System.String,System.Exception)
  langs:
  - csharp
  name: IsolatedStorageException
  nameWithType: IsolatedStorageException
  fullName: System.IO.IsolatedStorage.IsolatedStorageException
  type: Class
  summary: "分離ストレージ内の操作が失敗した場合にスローされる例外。"
  remarks: "`IsolatedStorageException`値は 0x80131450 HRESULT ISS_E_ISOSTORE を使用します。       分離ストレージの例外の最も一般的な例は次のとおりです。      -不足している必要な証拠。 分離ストレージでは、証拠 (アセンブリとその元に関する情報) が、コードの id を確認し、関連付けられた正しいファイルの領域に接続するために必要です。 この情報がない場合は、分離ストレージを使用できません。      -無効な操作です。 いくつか<xref:System.IO.FileStream>分離ストレージの操作はサポートされていません</xref:System.IO.FileStream>。       インスタンスの初期プロパティ値の一覧については`IsolatedStorageException`を参照してください、<xref:System.IO.IsolatedStorage.IsolatedStorageException.%23ctor%2A>コンス トラクター</xref:System.IO.IsolatedStorage.IsolatedStorageException.%23ctor%2A> 。"
  syntax:
    content: >-
      [System.Runtime.InteropServices.ComVisible(true)]

      public class IsolatedStorageException : Exception
  inheritance:
  - System.Exception
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.IO.IsolatedStorage.IsolatedStorageException.#ctor
  id: '#ctor'
  parent: System.IO.IsolatedStorage.IsolatedStorageException
  langs:
  - csharp
  name: IsolatedStorageException()
  nameWithType: IsolatedStorageException.IsolatedStorageException()
  fullName: System.IO.IsolatedStorage.IsolatedStorageException.IsolatedStorageException()
  type: Constructor
  assemblies:
  - mscorlib
  namespace: System.IO.IsolatedStorage
  summary: "新しいインスタンスを初期化、 <xref href=&quot;System.IO.IsolatedStorage.IsolatedStorageException&quot;> </xref>既定のプロパティを持つクラス。"
  remarks: "次の表は、 <xref:System.IO.IsolatedStorage.IsolatedStorageException>。</xref:System.IO.IsolatedStorage.IsolatedStorageException>のインスタンスの初期プロパティ値を示しています。      |プロパティ |値 |  |--------------|-----------|  |<xref:System.Exception.InnerException%2A>|`null`.|  |<xref:System.Exception.Message%2A>|ローカライズされたエラー メッセージ文字列 |</xref:System.Exception.Message%2A> </xref:System.Exception.InnerException%2A> 。"
  syntax:
    content: public IsolatedStorageException ();
    parameters: []
  overload: System.IO.IsolatedStorage.IsolatedStorageException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.IO.IsolatedStorage.IsolatedStorageException.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.IO.IsolatedStorage.IsolatedStorageException
  langs:
  - csharp
  name: IsolatedStorageException(String)
  nameWithType: IsolatedStorageException.IsolatedStorageException(String)
  fullName: System.IO.IsolatedStorage.IsolatedStorageException.IsolatedStorageException(String)
  type: Constructor
  assemblies:
  - mscorlib
  namespace: System.IO.IsolatedStorage
  summary: "新しいインスタンスを初期化、 <xref href=&quot;System.IO.IsolatedStorage.IsolatedStorageException&quot;> </xref>指定したエラー メッセージを使用します。"
  remarks: "次の表は、 <xref:System.IO.IsolatedStorage.IsolatedStorageException>。</xref:System.IO.IsolatedStorage.IsolatedStorageException>のインスタンスの初期プロパティ値を示しています。      |プロパティ |値 |  |--------------|-----------|  |<xref:System.Exception.InnerException%2A>|`null`.|  |<xref:System.Exception.Message%2A>|エラー メッセージ文字列 |</xref:System.Exception.Message%2A> </xref:System.Exception.InnerException%2A> 。"
  syntax:
    content: public IsolatedStorageException (string message);
    parameters:
    - id: message
      type: System.String
      description: "例外の原因を説明するエラー メッセージ。"
  overload: System.IO.IsolatedStorage.IsolatedStorageException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.IO.IsolatedStorage.IsolatedStorageException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  id: '#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)'
  parent: System.IO.IsolatedStorage.IsolatedStorageException
  langs:
  - csharp
  name: IsolatedStorageException(SerializationInfo,StreamingContext)
  nameWithType: IsolatedStorageException.IsolatedStorageException(SerializationInfo,StreamingContext)
  fullName: System.IO.IsolatedStorage.IsolatedStorageException.IsolatedStorageException(SerializationInfo,StreamingContext)
  type: Constructor
  assemblies:
  - mscorlib
  namespace: System.IO.IsolatedStorage
  summary: "新しいインスタンスを初期化、 <xref href=&quot;System.IO.IsolatedStorage.IsolatedStorageException&quot;> </xref>シリアル化されたデータを持つクラス。"
  remarks: "このコンス トラクターは、ストリームで送信された例外オブジェクトを再構成する逆シリアル化中に呼び出されます。"
  syntax:
    content: protected IsolatedStorageException (System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);
    parameters:
    - id: info
      type: System.Runtime.Serialization.SerializationInfo
      description: "シリアル化されたオブジェクト データを保持するオブジェクト。"
    - id: context
      type: System.Runtime.Serialization.StreamingContext
      description: "ソースまたは転送先に関する文脈情報。"
  overload: System.IO.IsolatedStorage.IsolatedStorageException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.IO.IsolatedStorage.IsolatedStorageException.#ctor(System.String,System.Exception)
  id: '#ctor(System.String,System.Exception)'
  parent: System.IO.IsolatedStorage.IsolatedStorageException
  langs:
  - csharp
  name: IsolatedStorageException(String,Exception)
  nameWithType: IsolatedStorageException.IsolatedStorageException(String,Exception)
  fullName: System.IO.IsolatedStorage.IsolatedStorageException.IsolatedStorageException(String,Exception)
  type: Constructor
  assemblies:
  - mscorlib
  namespace: System.IO.IsolatedStorage
  summary: "新しいインスタンスを初期化、 <xref href=&quot;System.IO.IsolatedStorage.IsolatedStorageException&quot;> </xref>指定したエラー メッセージおよびこの例外の原因となった内部例外への参照を持つクラス。"
  remarks: "前の例外への参照を含める必要があります前の例外の直接の結果としてスローされる例外、<xref:System.Exception.InnerException%2A>プロパティ</xref:System.Exception.InnerException%2A>。 <xref:System.Exception.InnerException%2A>プロパティは、コンス トラクターに渡されたものと同じ値を返しますまたは`null`場合、<xref:System.Exception.InnerException%2A>プロパティがコンス トラクターには、内部例外値を指定していません</xref:System.Exception.InnerException%2A></xref:System.Exception.InnerException%2A>。       次の表は、 <xref:System.IO.IsolatedStorage.IsolatedStorageException>。</xref:System.IO.IsolatedStorage.IsolatedStorageException>のインスタンスの初期プロパティ値を示しています。      |プロパティ |値 |  |--------------|-----------|  |<xref:System.Exception.InnerException%2A>|内部例外の参照 |。  |<xref:System.Exception.Message%2A>|エラー メッセージ文字列 |</xref:System.Exception.Message%2A> </xref:System.Exception.InnerException%2A> 。"
  syntax:
    content: public IsolatedStorageException (string message, Exception inner);
    parameters:
    - id: message
      type: System.String
      description: "例外の原因を説明するエラー メッセージ。"
    - id: inner
      type: System.Exception
      description: "現在の例外の原因となった例外。 場合、`inner`パラメーターではありません<xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;></xref>で現在の例外が発生、 <xref uid=&quot;langword_csharp_catch&quot; name=&quot;catch&quot; href=&quot;&quot;> </xref>ブロックは、内部例外を処理します。"
  overload: System.IO.IsolatedStorage.IsolatedStorageException.#ctor*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Exception
  isExternal: false
  name: System.Exception
- uid: System.IO.IsolatedStorage.IsolatedStorageException.#ctor
  parent: System.IO.IsolatedStorage.IsolatedStorageException
  isExternal: false
  name: IsolatedStorageException()
  nameWithType: IsolatedStorageException.IsolatedStorageException()
  fullName: System.IO.IsolatedStorage.IsolatedStorageException.IsolatedStorageException()
- uid: System.IO.IsolatedStorage.IsolatedStorageException.#ctor(System.String)
  parent: System.IO.IsolatedStorage.IsolatedStorageException
  isExternal: false
  name: IsolatedStorageException(String)
  nameWithType: IsolatedStorageException.IsolatedStorageException(String)
  fullName: System.IO.IsolatedStorage.IsolatedStorageException.IsolatedStorageException(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.IO.IsolatedStorage.IsolatedStorageException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  parent: System.IO.IsolatedStorage.IsolatedStorageException
  isExternal: false
  name: IsolatedStorageException(SerializationInfo,StreamingContext)
  nameWithType: IsolatedStorageException.IsolatedStorageException(SerializationInfo,StreamingContext)
  fullName: System.IO.IsolatedStorage.IsolatedStorageException.IsolatedStorageException(SerializationInfo,StreamingContext)
- uid: System.Runtime.Serialization.SerializationInfo
  parent: System.Runtime.Serialization
  isExternal: false
  name: SerializationInfo
  nameWithType: SerializationInfo
  fullName: System.Runtime.Serialization.SerializationInfo
- uid: System.Runtime.Serialization.StreamingContext
  parent: System.Runtime.Serialization
  isExternal: true
  name: StreamingContext
  nameWithType: StreamingContext
  fullName: System.Runtime.Serialization.StreamingContext
- uid: System.IO.IsolatedStorage.IsolatedStorageException.#ctor(System.String,System.Exception)
  parent: System.IO.IsolatedStorage.IsolatedStorageException
  isExternal: false
  name: IsolatedStorageException(String,Exception)
  nameWithType: IsolatedStorageException.IsolatedStorageException(String,Exception)
  fullName: System.IO.IsolatedStorage.IsolatedStorageException.IsolatedStorageException(String,Exception)
- uid: System.IO.IsolatedStorage.IsolatedStorageException.#ctor*
  parent: System.IO.IsolatedStorage.IsolatedStorageException
  isExternal: false
  name: IsolatedStorageException
  nameWithType: IsolatedStorageException.IsolatedStorageException
